---

- name: test db does not exist
  mysql_db:
    name: test
    state: absent
  when: not (ansible_check_mode and packages.changed)

- name: anonymous user does not exist
  mysql_user:
    name: ''
    host_all: yes
    state: absent
  when: not (ansible_check_mode and packages.changed)
