---

- name: create logical volume for mysql_data
  lvol:
    lv: mysql_data
    vg: "{{fs_vg_name|default('lvm.'+inventory_hostname)}}"
    size: 1g
    shrink: no

- name: filesystem for mysql data exists
  filesystem:
    dev: /dev/{{fs_vg_name|default('lvm.'+inventory_hostname)}}/mysql_data
    fstype: xfs

- name: mount point for /var/lib/mysql exists
  file:
    path: /var/lib/mysql
    state: directory
    setype: mysqld_db_t

- name: mount mysql data partition
  mount:
    src: /dev/{{fs_vg_name|default('lvm.'+inventory_hostname)}}/mysql_data
    path: /var/lib/mysql
    state: mounted
    fstype: xfs
    opts: defaults,nodev,nosuid,noexec

- name: mount point for /var/lib/mysql exists
  file:
    path: /var/lib/mysql
    state: directory
    setype: mysqld_db_t
    owner: mysql
    group: mysql

- name: resize data filesystem for mysql data
  filesystem:
    dev: /dev/{{fs_vg_name|default('lvm.'+inventory_hostname)}}/mysql_data
    fstype: xfs
    resizefs: yes

# log partition

- name: create logical volume for mysql logs
  lvol:
    lv: mysql_log
    vg: "{{fs_vg_name|default('lvm.'+inventory_hostname)}}"
    size: 1g
    shrink: no

- name: create filesystem for mysql logs
  filesystem:
    dev: /dev/{{fs_vg_name|default('lvm.'+inventory_hostname)}}/mysql_log
    fstype: xfs

- name: mount point exists
  file:
    path: /var/log/mysql
    state: directory
    setype: mysqld_log_t
    owner: mysql
    group: mysql

- name: mount mysql log partition
  mount:
    src: /dev/{{fs_vg_name|default('lvm.'+inventory_hostname)}}/mysql_log
    path: /var/log/mysql
    state: mounted
    fstype: xfs
    opts: defaults,nodev,nosuid,noexec

- name: mount point exists
  file:
    path: /var/log/mysql
    state: directory
    setype: mysqld_log_t
    owner: mysql
    group: mysql

- name: resize data filesystem for mysql logs
  filesystem:
    dev: /dev/{{fs_vg_name|default('lvm.'+inventory_hostname)}}/mysql_log
    fstype: xfs
    resizefs: yes

