---

- name: include OS specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: mysql server is installed
  package:
    name: "{{ mysqld.package }}"
    state: present

- name: additional packages are installed (make ansible happy)
  with_items: "{{ mysqld.additional_packages }}"
  package:
    name: "{{ item }}"

- name: my.cnf is in place
  template:
    src: my.cnf
    dest: /etc/my.cnf
    backup: true

- name: server.cnf is in place
  template:
    src: "{{ item }}"
    dest: "{{ mysqld.server_cnf_dest }}"
    backup: true
  with_first_found:
    - "{{ playbook_dir }}/templates/{{ server_cnf_template }}"
    - server.cnf
  notify: restart mysql

- debug: var=mysqld

- name: mysql daemon is running
  service:
    name: "{{ mysqld.daemon_name }}"
    state: started
    enabled: true
    use: systemd
  register: mysql_is_running

- name: installation is secured
  include_role:
    name: mariadb
    tasks_from: secure

- name: firewalld has mysql port open
  when: mysql.firewalld
  firewalld:
    immediate: true
    permanent: true
    service: mysql
    state: enabled
