---

- name: create filesystem for mysql_data
  include_role:
    - name: fs
      fs_mountpoint: /var/lib/mysql
      fs_vg_name: "{{ ansible_lvm.vgs.keys()[0] }}"
      fs_lv_name: mysql
      fs_size: 20g
      fs_fstype: xfs
      fs_mountoptions: defaults,nodev,nosuid

- name: create filesystem for mysql_logs


- name: mount point for /var/lib/mysql exists
  file:
    path: /var/lib/mysql
    state: directory
    setype: mysqld_db_t

- name: mount mysql data partition
  mount:
    src: /dev/{{fs_vg_name|default('lvm.'+inventory_hostname)}}/mysql_data
    path: /var/lib/mysql
    state: mounted
    fstype: xfs
    opts: defaults,nodev,nosuid,noexec

- name: mount point for /var/lib/mysql exists
  file:
    path: /var/lib/mysql
    state: directory
    setype: mysqld_db_t
    owner: mysql
    group: mysql

- name: resize data filesystem for mysql data
  filesystem:
    dev: /dev/{{fs_vg_name|default('lvm.'+inventory_hostname)}}/mysql_data
    fstype: xfs
    resizefs: yes

# log partition

- name: create logical volume for mysql logs
  lvol:
    lv: mysql_log
    vg: "{{fs_vg_name|default('lvm.'+inventory_hostname)}}"
    size: 1g
    shrink: no

- name: create filesystem for mysql logs
  filesystem:
    dev: /dev/{{fs_vg_name|default('lvm.'+inventory_hostname)}}/mysql_log
    fstype: xfs

- name: mount point exists
  file:
    path: /var/log/mysql
    state: directory
    setype: mysqld_log_t
    owner: mysql
    group: mysql

- name: mount mysql log partition
  mount:
    src: /dev/{{fs_vg_name|default('lvm.'+inventory_hostname)}}/mysql_log
    path: /var/log/mysql
    state: mounted
    fstype: xfs
    opts: defaults,nodev,nosuid,noexec

- name: mount point exists
  file:
    path: /var/log/mysql
    state: directory
    setype: mysqld_log_t
    owner: mysql
    group: mysql

- name: resize data filesystem for mysql logs
  filesystem:
    dev: /dev/{{fs_vg_name|default('lvm.'+inventory_hostname)}}/mysql_log
    fstype: xfs
    resizefs: yes

